name: Python
on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: flake8
        uses: py-actions/flake8@v2
        with:
          ignore: "E402"
          max-line-length: 120
          path: "python"

  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd python
          python3 -m pip install --upgrade build

      - name: Build
        run: |
          cd python
          python3 -m build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          cd python
          python3 -m pip install --upgrade build

      - name: Build
        run: |
          cd python
          python3 -m build

      - name: publish to pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
