name: Rust
on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.88.0

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: rustup
        run: rustup default $RUST_VERSION
      - name: cargo-fmt
        run: |
          set -euxo pipefail
          cd rust
          rustup component add rustfmt 
          rustfmt --version
          cargo fmt --all -- --check
      - name: cargo-clippy
        run: |
          cd rust
          rustup component add clippy
          cargo clippy --all-targets --all-features -- --no-deps -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: rustup
        run: rustup default $RUST_VERSION
      - name: build
        run: |
          cd rust
          cargo build --examples
      - name: test
        run: |
          set -euxo pipefail
          cd rust
          cargo test --tests --all-features -- --show-output --test-threads=1


  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
      - name: rustup
        run: rustup default $RUST_VERSION
      - name: publish
        env:
          CRATES_API_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
        run: |
          set -euxo pipefail
          cd rust
          cargo publish --token $CRATES_API_TOKEN
